### ISSUE TITLE
Review and refine `GitHub` issue templates

### ISSUE THREAD

**Issue by nandordudas** [nandordudas/multiplayer-pong#11]
### Sprint

Sprint 1: Foundation

### Epic

Project Setup

### Story Points

1

### Task Description

Update existing issue templates because they are not accurate.

### Acceptance Criteria

- [ ] contain required only fields

### Cyclomatic Complexity Target

0

### Required Checks

- [X] This task follows the TypeScript strict mode guidelines
- [X] Performance implications have been considered
- [X] Security implications have been considered
